In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,4]

In [3]:
np.asarray(l)

array([1, 2, 3, 4, 4])

In [4]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones_like(l)

array([1, 1, 1, 1, 1])

In [7]:
np.ones_like(np.array(l))

array([1, 1, 1, 1, 1])

In [8]:
np.zeros((3,4)) + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [9]:
np.empty((4,3))

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
np.empty((3,4,2))

array([[[4.67296746e-307, 1.69121096e-306],
        [7.56595733e-307, 7.56587585e-307],
        [1.37961302e-306, 1.05699242e-307],
        [8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306],
        [8.90092016e-307, 1.02361342e-306],
        [6.89804133e-307, 8.90104239e-307],
        [8.90098127e-307, 8.90111708e-307]],

       [[6.23054633e-307, 9.34598926e-307],
        [1.42417629e-306, 1.11260687e-306],
        [1.15710088e-306, 7.56597091e-307],
        [9.34598925e-307, 8.34446411e-308]]])

In [13]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [21]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [25]:
np.linspace(2,6,10, endpoint = False, retstep = True) #whne retsetp is used Tuple is output, doesn't hav ereshape

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [27]:
np.logspace(2,6,15, base = 10)

array([1.00000000e+02, 1.93069773e+02, 3.72759372e+02, 7.19685673e+02,
       1.38949549e+03, 2.68269580e+03, 5.17947468e+03, 1.00000000e+04,
       1.93069773e+04, 3.72759372e+04, 7.19685673e+04, 1.38949549e+05,
       2.68269580e+05, 5.17947468e+05, 1.00000000e+06])

In [54]:
a = np.random.randint(4,20, size = (4,4))

In [55]:
a

array([[18, 10, 15,  4],
       [13, 18, 16,  6],
       [17,  4,  4, 13],
       [10, 13,  7, 17]])

In [56]:
a.max()

18

In [57]:
a.max(axis =1 )

array([18, 18, 17, 17])

In [58]:
a.max(axis =0 )

array([18, 18, 16, 17])

In [59]:
pow(a,3)
a**3

array([[5832, 1000, 3375,   64],
       [2197, 5832, 4096,  216],
       [4913,   64,   64, 2197],
       [1000, 2197,  343, 4913]], dtype=int32)

In [61]:
b = np.array([2,4,3,5])

In [62]:
a+b # adds this row to every row

array([[20, 14, 18,  9],
       [15, 22, 19, 11],
       [19,  8,  7, 18],
       [12, 17, 10, 22]])

In [63]:
a+b.T

array([[20, 14, 18,  9],
       [15, 22, 19, 11],
       [19,  8,  7, 18],
       [12, 17, 10, 22]])

In [53]:
b.shape # for transpose or rotate the matrix , we need second other dimension

(4,)

In [64]:
a+b.reshape(1,-1).T

array([[20, 12, 17,  6],
       [17, 22, 20, 10],
       [20,  7,  7, 16],
       [15, 18, 12, 22]])

In [65]:
a+b.reshape(-1,1)

array([[20, 12, 17,  6],
       [17, 22, 20, 10],
       [20,  7,  7, 16],
       [15, 18, 12, 22]])

In [66]:
np.sqrt(a)

array([[4.24264069, 3.16227766, 3.87298335, 2.        ],
       [3.60555128, 4.24264069, 4.        , 2.44948974],
       [4.12310563, 2.        , 2.        , 3.60555128],
       [3.16227766, 3.60555128, 2.64575131, 4.12310563]])

In [67]:
np.exp(a)

array([[6.56599691e+07, 2.20264658e+04, 3.26901737e+06, 5.45981500e+01],
       [4.42413392e+05, 6.56599691e+07, 8.88611052e+06, 4.03428793e+02],
       [2.41549528e+07, 5.45981500e+01, 5.45981500e+01, 4.42413392e+05],
       [2.20264658e+04, 4.42413392e+05, 1.09663316e+03, 2.41549528e+07]])

In [68]:
np.log2(a)

array([[4.169925  , 3.32192809, 3.9068906 , 2.        ],
       [3.70043972, 4.169925  , 4.        , 2.5849625 ],
       [4.08746284, 2.        , 2.        , 3.70043972],
       [3.32192809, 3.70043972, 2.80735492, 4.08746284]])

In [126]:
x = np.array([1,2,3])

In [127]:
id(x)

2289343286992

In [128]:
y = x # deep copy

In [129]:
id(y)

2289343286992

In [130]:
z = np.copy(x) #sollow copy

In [131]:
id(z)

2289343285360

In [132]:
x[0] = 10

In [133]:
id(x)

2289343286992

In [134]:
y

array([10,  2,  3])

In [135]:
id(y) #x, y having same id as both are deep copy to each other  but not element wise i.e, id(x[0])  not sameas id(y[0])

2289343286992

In [136]:
z

array([1, 2, 3])

In [137]:
id(z)

2289343285360

In [138]:
id(x[0])

2289336744656

In [139]:
id(y[0])

2289336744336

In [141]:
id(x) == id(y) # looks okay

True

In [150]:
id(x[0]) == id(y[0]) #looks weird, right?

True

In [151]:
c = np.array([5,4,6])

In [154]:
id(x[0]) == id(c[0]) # looks more weird.

True

# explore what is happening above?
explanantion need to write

In [144]:
c = 'bhargav'

In [145]:
id(c) == id(x[0]) # this is clue

False

In [121]:
x = x+2 #when new allocation is happened to X it's location(ID) will be changed , but not for y and vice versa

In [122]:
x

array([12,  4,  5])

In [123]:
id(x)

2289343285552

In [124]:
y

array([10,  2,  3])

In [125]:
id(y)

2289343286224

In [105]:
z

array([1, 2, 3])

In [106]:
x[1 ]  = 100

In [107]:
y

array([10,  2,  3])