In [22]:
import pandas as pd
import numpy as np

In [23]:
 data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [24]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [25]:
data.dropna() #drops all NaN values by default rows as axis = 0

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [26]:
data.dropna(axis = 1) # w.r.t column

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  SibSp  Parch  \
0                              Braund, Mr. Owen Harris    male      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                               Heikkinen, Miss. Laina  female      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                             Allen, Mr. William Henry    male      0      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male      0      0   
887                       Graham, Miss. Margaret Edith  female      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female      1      2   
889                              Behr, Mr. Karl Howell    male      0      0   
890                                Dooley, Mr. Patrick    male      0      0   

               Ticket     Fare  
0           A/5 21171   7.2500  
1            PC 17599  71.2833  
2    STON/O2. 3101282   7.9250  
3              113803  53.1000  
4              373450   8.0500  
..                ...      ...  
886            211536  13.0000  
887            112053  30.0000  
888        W./C. 6607  23.4500  
889            111369  30.0000  
890            370376   7.7500  

[891 rows x 9 columns]

In [27]:
data # no data altered while performing above operations.

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [28]:
# data = data.dropna()
data.dropna(inplace = True)

In [29]:
data

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [30]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [31]:
 data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [32]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [33]:
data.dropna(axis = 1 ,thresh = 800) # is keep the column , it should have 800 non-NaN values

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  SibSp  Parch  \
0                              Braund, Mr. Owen Harris    male      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                               Heikkinen, Miss. Laina  female      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                             Allen, Mr. William Henry    male      0      0   
..                                                 ...     ...    ...    ...   
886                              Montvila, Rev. Juozas    male      0      0   
887                       Graham, Miss. Margaret Edith  female      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female      1      2   
889                              Behr, Mr. Karl Howell    male      0      0   
890                                Dooley, Mr. Patrick    male      0      0   

               Ticket     Fare Embarked  
0           A/5 21171   7.2500        S  
1            PC 17599  71.2833        C  
2    STON/O2. 3101282   7.9250        S  
3              113803  53.1000        S  
4              373450   8.0500        S  
..                ...      ...      ...  
886            211536  13.0000        S  
887            112053  30.0000        S  
888        W./C. 6607  23.4500        S  
889            111369  30.0000        C  
890            370376   7.7500        Q  

[891 rows x 10 columns]

In [34]:
data.dropna(axis = 1, how = 'all') #by default how='any'

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [35]:
data.fillna(value = 'bhargav')

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex      Age  \
0                              Braund, Mr. Owen Harris    male     22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female     38.0   
2                               Heikkinen, Miss. Laina  female     26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female     35.0   
4                             Allen, Mr. William Henry    male     35.0   
..                                                 ...     ...      ...   
886                              Montvila, Rev. Juozas    male     27.0   
887                       Graham, Miss. Margaret Edith  female     19.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  bhargav   
889                              Behr, Mr. Karl Howell    male     26.0   
890                                Dooley, Mr. Patrick    male     32.0   

     SibSp  Parch            Ticket     Fare    Cabin Embarked  
0        1      0         A/5 21171   7.2500  bhargav        S  
1        1      0          PC 17599  71.2833      C85        C  
2        0      0  STON/O2. 3101282   7.9250  bhargav        S  
3        1      0            113803  53.1000     C123        S  
4        0      0            373450   8.0500  bhargav        S  
..     ...    ...               ...      ...      ...      ...  
886      0      0            211536  13.0000  bhargav        S  
887      0      0            112053  30.0000      B42        S  
888      1      2        W./C. 6607  23.4500  bhargav        S  
889      0      0            111369  30.0000     C148        C  
890      0      0            370376   7.7500  bhargav        Q  

[891 rows x 12 columns]

In [36]:
data.fillna(value=data['Age'].mean())

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     SibSp  Parch            Ticket     Fare      Cabin Embarked  
0        1      0         A/5 21171   7.2500  29.699118        S  
1        1      0          PC 17599  71.2833        C85        C  
2        0      0  STON/O2. 3101282   7.9250  29.699118        S  
3        1      0            113803  53.1000       C123        S  
4        0      0            373450   8.0500  29.699118        S  
..     ...    ...               ...      ...        ...      ...  
886      0      0            211536  13.0000  29.699118        S  
887      0      0            112053  30.0000        B42        S  
888      1      2        W./C. 6607  23.4500  29.699118        S  
889      0      0            111369  30.0000       C148        C  
890      0      0            370376   7.7500  29.699118        Q  

[891 rows x 12 columns]

In [38]:
data.groupby('Survived').describe()

PassengerId                                                     \
               count        mean         std  min     25%    50%    75%   
Survived                                                                  
0              549.0  447.016393  260.640469  1.0  211.00  455.0  675.0   
1              342.0  444.368421  252.358840  2.0  250.75  439.5  651.5   

                Pclass            ... Parch        Fare                        \
            max  count      mean  ...   75%  max  count       mean        std   
Survived                          ...                                           
0         891.0  549.0  2.531876  ...   0.0  6.0  549.0  22.117887  31.388207   
1         890.0  342.0  1.950292  ...   1.0  5.0  342.0  48.395408  66.596998   

                                              
          min      25%   50%   75%       max  
Survived                                      
0         0.0   7.8542  10.5  26.0  263.0000  
1         0.0  12.4750  26.0  57.0  512.3292  

[2 rows x 48 columns]

In [39]:
data.groupby('Survived').describe()['PassengerId']

count        mean         std  min     25%    50%    75%    max
Survived                                                                 
0         549.0  447.016393  260.640469  1.0  211.00  455.0  675.0  891.0
1         342.0  444.368421  252.358840  2.0  250.75  439.5  651.5  890.0

In [40]:
data.groupby('Survived').describe()['PassengerId'].T

Survived           0           1
count     549.000000  342.000000
mean      447.016393  444.368421
std       260.640469  252.358840
min         1.000000    2.000000
25%       211.000000  250.750000
50%       455.000000  439.500000
75%       675.000000  651.500000
max       891.000000  890.000000

In [41]:
data.groupby('Survived').describe()['PassengerId'].transpose()

Survived           0           1
count     549.000000  342.000000
mean      447.016393  444.368421
std       260.640469  252.358840
min         1.000000    2.000000
25%       211.000000  250.750000
50%       455.000000  439.500000
75%       675.000000  651.500000
max       891.000000  890.000000

In [98]:
df1 = pd.read_csv(r'C:\Users\bharg\PycharmProjects\jupyter\bank\bank.csv', sep = ';') # bank marketing dataset UCI dataset

In [99]:
l=[]
for i in df1['education'].unique():
    l.append(df1[df1['education'] == i])

In [100]:
df2 = l[0]

In [101]:
df3 = l[1]
df4 = l[2]
df5 = l[3]

In [51]:
df2

age            job   marital education default  balance housing loan  \
0      30     unemployed   married   primary      no     1787      no   no   
9      43       services   married   primary      no      -88     yes  yes   
18     25    blue-collar    single   primary      no     -221     yes   no   
26     55    blue-collar   married   primary      no      627     yes   no   
36     78        retired  divorced   primary      no      229      no   no   
...   ...            ...       ...       ...     ...      ...     ...  ...   
4480   23    blue-collar   married   primary      no     1158     yes   no   
4485   53    blue-collar   married   primary      no      238     yes   no   
4486   37    blue-collar   married   primary      no      378     yes   no   
4499   45    blue-collar  divorced   primary      no      942      no   no   
4503   60  self-employed   married   primary      no      362      no  yes   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   19   oct        79         1     -1         0  unknown   no  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
26      unknown    5   may       247         1     -1         0  unknown   no  
36    telephone   22   oct        97         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4480   cellular   16   apr       743         1     -1         0  unknown   no  
4485   cellular   11   may       238         2    361         5  failure   no  
4486    unknown    9   may       514         1     -1         0  unknown   no  
4499   cellular   21   nov       362         1     -1         0  unknown   no  
4503   cellular   29   jul       816         6     -1         0  unknown  yes  

[678 rows x 17 columns]

In [52]:
df3

age          job  marital  education default  balance housing loan  \
1      33     services  married  secondary      no     4789     yes  yes   
4      59  blue-collar  married  secondary      no        0     yes   no   
7      39   technician  married  secondary      no      147     yes   no   
10     39     services  married  secondary      no     9374     yes   no   
11     43       admin.  married  secondary      no      264     yes   no   
...   ...          ...      ...        ...     ...      ...     ...  ...   
4514   38  blue-collar  married  secondary      no     1205     yes   no   
4515   32     services   single  secondary      no      473     yes   no   
4516   33     services  married  secondary      no     -333     yes   no   
4518   57   technician  married  secondary      no      295      no   no   
4519   28  blue-collar  married  secondary      no     1137      no   no   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
1     cellular   11   may       220         1    339         4  failure  no  
4      unknown    5   may       226         1     -1         0  unknown  no  
7     cellular    6   may       151         2     -1         0  unknown  no  
10     unknown   20   may       273         1     -1         0  unknown  no  
11    cellular   17   apr       113         2     -1         0  unknown  no  
...        ...  ...   ...       ...       ...    ...       ...      ...  ..  
4514  cellular   20   apr        45         4    153         1  failure  no  
4515  cellular    7   jul       624         5     -1         0  unknown  no  
4516  cellular   30   jul       329         5     -1         0  unknown  no  
4518  cellular   19   aug       151        11     -1         0  unknown  no  
4519  cellular    6   feb       129         4    211         3    other  no  

[2306 rows x 17 columns]

### 

In [47]:
"sudh" + "kumar"

'sudhkumar'

In [50]:
pd.concat([df2,df3])

age          job   marital  education default  balance housing loan  \
0      30   unemployed   married    primary      no     1787      no   no   
9      43     services   married    primary      no      -88     yes  yes   
18     25  blue-collar    single    primary      no     -221     yes   no   
26     55  blue-collar   married    primary      no      627     yes   no   
36     78      retired  divorced    primary      no      229      no   no   
...   ...          ...       ...        ...     ...      ...     ...  ...   
4514   38  blue-collar   married  secondary      no     1205     yes   no   
4515   32     services    single  secondary      no      473     yes   no   
4516   33     services   married  secondary      no     -333     yes   no   
4518   57   technician   married  secondary      no      295      no   no   
4519   28  blue-collar   married  secondary      no     1137      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   19   oct        79         1     -1         0  unknown   no  
9      cellular   17   apr       313         1    147         2  failure   no  
18      unknown   23   may       250         1     -1         0  unknown   no  
26      unknown    5   may       247         1     -1         0  unknown   no  
36    telephone   22   oct        97         1     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
4514   cellular   20   apr        45         4    153         1  failure   no  
4515   cellular    7   jul       624         5     -1         0  unknown   no  
4516   cellular   30   jul       329         5     -1         0  unknown   no  
4518   cellular   19   aug       151        11     -1         0  unknown   no  
4519   cellular    6   feb       129         4    211         3    other   no  

[2984 rows x 17 columns]

In [102]:
df2 = df2.head()

In [103]:
df3 = df3.head()

In [55]:
df2

age          job   marital education default  balance housing loan  \
0    30   unemployed   married   primary      no     1787      no   no   
9    43     services   married   primary      no      -88     yes  yes   
18   25  blue-collar    single   primary      no     -221     yes   no   
26   55  blue-collar   married   primary      no      627     yes   no   
36   78      retired  divorced   primary      no      229      no   no   

      contact  day month  duration  campaign  pdays  previous poutcome    y  
0    cellular   19   oct        79         1     -1         0  unknown   no  
9    cellular   17   apr       313         1    147         2  failure   no  
18    unknown   23   may       250         1     -1         0  unknown   no  
26    unknown    5   may       247         1     -1         0  unknown   no  
36  telephone   22   oct        97         1     -1         0  unknown  yes

In [56]:
df3

age          job  marital  education default  balance housing loan  \
1    33     services  married  secondary      no     4789     yes  yes   
4    59  blue-collar  married  secondary      no        0     yes   no   
7    39   technician  married  secondary      no      147     yes   no   
10   39     services  married  secondary      no     9374     yes   no   
11   43       admin.  married  secondary      no      264     yes   no   

     contact  day month  duration  campaign  pdays  previous poutcome   y  
1   cellular   11   may       220         1    339         4  failure  no  
4    unknown    5   may       226         1     -1         0  unknown  no  
7   cellular    6   may       151         2     -1         0  unknown  no  
10   unknown   20   may       273         1     -1         0  unknown  no  
11  cellular   17   apr       113         2     -1         0  unknown  no

In [57]:
pd.concat([df2,df3]) #concatanation is along axis = 0

age          job   marital  education default  balance housing loan  \
0    30   unemployed   married    primary      no     1787      no   no   
9    43     services   married    primary      no      -88     yes  yes   
18   25  blue-collar    single    primary      no     -221     yes   no   
26   55  blue-collar   married    primary      no      627     yes   no   
36   78      retired  divorced    primary      no      229      no   no   
1    33     services   married  secondary      no     4789     yes  yes   
4    59  blue-collar   married  secondary      no        0     yes   no   
7    39   technician   married  secondary      no      147     yes   no   
10   39     services   married  secondary      no     9374     yes   no   
11   43       admin.   married  secondary      no      264     yes   no   

      contact  day month  duration  campaign  pdays  previous poutcome    y  
0    cellular   19   oct        79         1     -1         0  unknown   no  
9    cellular   17   apr       313         1    147         2  failure   no  
18    unknown   23   may       250         1     -1         0  unknown   no  
26    unknown    5   may       247         1     -1         0  unknown   no  
36  telephone   22   oct        97         1     -1         0  unknown  yes  
1    cellular   11   may       220         1    339         4  failure   no  
4     unknown    5   may       226         1     -1         0  unknown   no  
7    cellular    6   may       151         2     -1         0  unknown   no  
10    unknown   20   may       273         1     -1         0  unknown   no  
11   cellular   17   apr       113         2     -1         0  unknown   no

In [58]:
 pd.concat([df2,df3],axis = 1)

age          job   marital education default  balance housing loan  \
0   30.0   unemployed   married   primary      no   1787.0      no   no   
9   43.0     services   married   primary      no    -88.0     yes  yes   
18  25.0  blue-collar    single   primary      no   -221.0     yes   no   
26  55.0  blue-collar   married   primary      no    627.0     yes   no   
36  78.0      retired  divorced   primary      no    229.0      no   no   
1    NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
4    NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
7    NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
10   NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   
11   NaN          NaN       NaN       NaN     NaN      NaN     NaN  NaN   

      contact   day  ... loan   contact   day  month  duration campaign  \
0    cellular  19.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
9    cellular  17.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
18    unknown  23.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
26    unknown   5.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
36  telephone  22.0  ...  NaN       NaN   NaN    NaN       NaN      NaN   
1         NaN   NaN  ...  yes  cellular  11.0    may     220.0      1.0   
4         NaN   NaN  ...   no   unknown   5.0    may     226.0      1.0   
7         NaN   NaN  ...   no  cellular   6.0    may     151.0      2.0   
10        NaN   NaN  ...   no   unknown  20.0    may     273.0      1.0   
11        NaN   NaN  ...   no  cellular  17.0    apr     113.0      2.0   

    pdays  previous poutcome    y  
0     NaN       NaN      NaN  NaN  
9     NaN       NaN      NaN  NaN  
18    NaN       NaN      NaN  NaN  
26    NaN       NaN      NaN  NaN  
36    NaN       NaN      NaN  NaN  
1   339.0       4.0  failure   no  
4    -1.0       0.0  unknown   no  
7    -1.0       0.0  unknown   no  
10   -1.0       0.0  unknown   no  
11   -1.0       0.0  unknown   no  

[10 rows x 34 columns]

In [106]:
df2 = df2.head()[['age','job','marital']]

In [107]:
df2

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [108]:
df3= df3.head()[['age','job','marital','balance']]

In [109]:
df3

age          job  marital  balance
1    33     services  married     4789
4    59  blue-collar  married        0
7    39   technician  married      147
10   39     services  married     9374
11   43       admin.  married      264

In [63]:
 pd.concat([df2,df3],axis = 1)

age          job   marital   age          job  marital  balance
0   30.0   unemployed   married   NaN          NaN      NaN      NaN
9   43.0     services   married   NaN          NaN      NaN      NaN
18  25.0  blue-collar    single   NaN          NaN      NaN      NaN
26  55.0  blue-collar   married   NaN          NaN      NaN      NaN
36  78.0      retired  divorced   NaN          NaN      NaN      NaN
1    NaN          NaN       NaN  33.0     services  married   4789.0
4    NaN          NaN       NaN  59.0  blue-collar  married      0.0
7    NaN          NaN       NaN  39.0   technician  married    147.0
10   NaN          NaN       NaN  39.0     services  married   9374.0
11   NaN          NaN       NaN  43.0       admin.  married    264.0

In [64]:
df7 =  pd.concat([df2,df3],axis = 1)

In [65]:
df7 # how to select age column now?

age          job   marital   age          job  marital  balance
0   30.0   unemployed   married   NaN          NaN      NaN      NaN
9   43.0     services   married   NaN          NaN      NaN      NaN
18  25.0  blue-collar    single   NaN          NaN      NaN      NaN
26  55.0  blue-collar   married   NaN          NaN      NaN      NaN
36  78.0      retired  divorced   NaN          NaN      NaN      NaN
1    NaN          NaN       NaN  33.0     services  married   4789.0
4    NaN          NaN       NaN  59.0  blue-collar  married      0.0
7    NaN          NaN       NaN  39.0   technician  married    147.0
10   NaN          NaN       NaN  39.0     services  married   9374.0
11   NaN          NaN       NaN  43.0       admin.  married    264.0

In [66]:
df7['age']

age   age
0   30.0   NaN
9   43.0   NaN
18  25.0   NaN
26  55.0   NaN
36  78.0   NaN
1    NaN  33.0
4    NaN  59.0
7    NaN  39.0
10   NaN  39.0
11   NaN  43.0

In [68]:
df7['age'][0]

KeyError: 0

In [69]:
df7.iloc[:,3] 

0      NaN
9      NaN
18     NaN
26     NaN
36     NaN
1     33.0
4     59.0
7     39.0
10    39.0
11    43.0
Name: age, dtype: float64

# loc always takes named indexes

# where as iloc takes integer indexes

In [70]:
df7.iloc[:,0] 

0     30.0
9     43.0
18    25.0
26    55.0
36    78.0
1      NaN
4      NaN
7      NaN
10     NaN
11     NaN
Name: age, dtype: float64

In [71]:
df7.iloc[3:6,1:3] 

job   marital
26  blue-collar   married
36      retired  divorced
1           NaN       NaN

In [72]:
df7.iloc[[3,6],[1,3]]

job   age
26  blue-collar   NaN
4           NaN  59.0

In [73]:
df7

age          job   marital   age          job  marital  balance
0   30.0   unemployed   married   NaN          NaN      NaN      NaN
9   43.0     services   married   NaN          NaN      NaN      NaN
18  25.0  blue-collar    single   NaN          NaN      NaN      NaN
26  55.0  blue-collar   married   NaN          NaN      NaN      NaN
36  78.0      retired  divorced   NaN          NaN      NaN      NaN
1    NaN          NaN       NaN  33.0     services  married   4789.0
4    NaN          NaN       NaN  59.0  blue-collar  married      0.0
7    NaN          NaN       NaN  39.0   technician  married    147.0
10   NaN          NaN       NaN  39.0     services  married   9374.0
11   NaN          NaN       NaN  43.0       admin.  married    264.0

In [74]:
df2

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [75]:
df2.iloc[1:3,1:]

job  marital
9      services  married
18  blue-collar   single

In [76]:
df2.loc[[9,18],['job','marital']]

job  marital
9      services  married
18  blue-collar   single

In [78]:
df2.iloc[[1,2],[1,2]]

job  marital
9      services  married
18  blue-collar   single

In [79]:
df2.iloc[[1,2],[0,2]]

age  marital
9    43  married
18   25   single

In [80]:
df2.loc[[9,18],['age','marital']]

age  marital
9    43  married
18   25   single

In [83]:
df2

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [84]:
df3

age          job  marital  balance
1    33     services  married     4789
4    59  blue-collar  married        0
7    39   technician  married      147
10   39     services  married     9374
11   43       admin.  married      264

### 

In [82]:
pd.merge(df2,df3)

Empty DataFrame
Columns: [age, job, marital, balance]
Index: []

In [85]:
pd.merge(df2,df3, on ='age')

age     job_x marital_x   job_y marital_y  balance
0   43  services   married  admin.   married      264

In [87]:
pd.merge(df2,df3, on ='age', how = 'left') # it will take total left dataframe and merge on that with same Age from roght data frame

age        job_x marital_x   job_y marital_y  balance
0   30   unemployed   married     NaN       NaN      NaN
1   43     services   married  admin.   married    264.0
2   25  blue-collar    single     NaN       NaN      NaN
3   55  blue-collar   married     NaN       NaN      NaN
4   78      retired  divorced     NaN       NaN      NaN

In [88]:
 pd.merge(df2,df3, on ='age', how = 'outer')

age        job_x marital_x        job_y marital_y  balance
0   30   unemployed   married          NaN       NaN      NaN
1   43     services   married       admin.   married    264.0
2   25  blue-collar    single          NaN       NaN      NaN
3   55  blue-collar   married          NaN       NaN      NaN
4   78      retired  divorced          NaN       NaN      NaN
5   33          NaN       NaN     services   married   4789.0
6   59          NaN       NaN  blue-collar   married      0.0
7   39          NaN       NaN   technician   married    147.0
8   39          NaN       NaN     services   married   9374.0

#  This HOW is works as venn diagram
Inner is common in venn diagram A intersection B

Outer is A-B

left is A+ A intersection B

Right is B+ A intersection B

In [89]:
df2

age          job   marital
0    30   unemployed   married
9    43     services   married
18   25  blue-collar    single
26   55  blue-collar   married
36   78      retired  divorced

In [90]:
df3

age          job  marital  balance
1    33     services  married     4789
4    59  blue-collar  married        0
7    39   technician  married      147
10   39     services  married     9374
11   43       admin.  married      264

In [111]:
df2.join(df3)

ValueError: columns overlap but no suffix specified: Index(['age', 'job', 'marital'], dtype='object')

In [112]:
df2.join(df3, on = 'age')

ValueError: columns overlap but no suffix specified: Index(['age', 'job', 'marital'], dtype='object')

In [114]:
df3 = df3.rename(columns={'job': 'job1', 'marital': 'marital1'})

In [115]:
df2.join(df3, on = 'age')

ValueError: columns overlap but no suffix specified: Index(['age'], dtype='object')

In [116]:
df2.set_index('age')

job   marital
age                       
30    unemployed   married
43      services   married
25   blue-collar    single
55   blue-collar   married
78       retired  divorced

In [117]:
df3 = df3.set_index('age')

In [118]:
df2 =df2.set_index('age')

In [119]:
df2.join(df3, on ='age')

job   marital    job1 marital1  balance
age                                                 
30    unemployed   married     NaN      NaN      NaN
43      services   married  admin.  married    264.0
25   blue-collar    single     NaN      NaN      NaN
55   blue-collar   married     NaN      NaN      NaN
78       retired  divorced     NaN      NaN      NaN

In [120]:
df2.join(df3, how = 'inner')

job  marital    job1 marital1  balance
age                                             
43   services  married  admin.  married      264

In [121]:
pd.merge(df2,df3)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [122]:
df2.join(df3)

job   marital    job1 marital1  balance
age                                                 
25   blue-collar    single     NaN      NaN      NaN
30    unemployed   married     NaN      NaN      NaN
43      services   married  admin.  married    264.0
55   blue-collar   married     NaN      NaN      NaN
78       retired  divorced     NaN      NaN      NaN

In [124]:
pd.merge(df2, df3, left_on='job', right_on= 'job1')

job  marital         job1 marital1  balance
0     services  married     services  married     4789
1     services  married     services  married     9374
2  blue-collar   single  blue-collar  married        0
3  blue-collar  married  blue-collar  married        0

In [125]:
df2

job   marital
age                       
30    unemployed   married
43      services   married
25   blue-collar    single
55   blue-collar   married
78       retired  divorced

In [126]:
df3

job1 marital1  balance
age                               
33      services  married     4789
59   blue-collar  married        0
39    technician  married      147
39      services  married     9374
43        admin.  married      264

In [1]:
  import pandas as pd

In [2]:
pd.DataFrame({'col1' : [1,2,4,5,6],
              'col2': [45,47,87,5],
              'col3': 'Bhargav is good by'
})

ValueError: All arrays must be of the same length

In [4]:
pd.DataFrame({'col1' : [1,2,4,5,6],
              'col2': [45,47,87,5,87],
              'col3': 'Bhargav is good boy'
})

col1  col2                 col3
0     1    45  Bhargav is good boy
1     2    47  Bhargav is good boy
2     4    87  Bhargav is good boy
3     5     5  Bhargav is good boy
4     6    87  Bhargav is good boy

In [5]:
'Bhargav is good boy'.split()

['Bhargav', 'is', 'good', 'boy']

In [7]:
pd.DataFrame({'col1' : [1,2,4,5,6],
              'col2': [45,47,87,5,87],
              'col3': 'Bhargav is good boy among'.split()
})

col1  col2     col3
0     1    45  Bhargav
1     2    47       is
2     4    87     good
3     5     5      boy
4     6    87    among

In [8]:
df = pd.DataFrame({'col1' : [1,2,4,5,6],
              'col2': [45,47,87,5,87],
              'col3': 'Bhargav is good boy among'.split()
})

In [10]:
df['col4'] = df['col1']**2

In [11]:
df

col1  col2     col3  col4
0     1    45  Bhargav     1
1     2    47       is     4
2     4    87     good    16
3     5     5      boy    25
4     6    87    among    36

In [15]:
df['col5'] = df['col3'].str[0]
df

col1  col2     col3  col4 col5
0     1    45  Bhargav     1    B
1     2    47       is     4    i
2     4    87     good    16    g
3     5     5      boy    25    b
4     6    87    among    36    a

if col5 = b then  col6 = B , if not S col6 =Z

In [16]:
def test(a):
    return a**2

In [17]:
df['col_4'] = df['col1'].apply(test)

In [18]:
df

col1  col2     col3  col4 col5  col_4
0     1    45  Bhargav     1    B      1
1     2    47       is     4    i      4
2     4    87     good    16    g     16
3     5     5      boy    25    b     25
4     6    87    among    36    a     36

In [22]:
def test1(a):
    if a == 'b':
        return 'B'
    else:
        return 'Z'

In [23]:
df['col6'] = df['col5'].apply(test1)

In [24]:
df

col1  col2     col3  col4 col5  col_4 col6
0     1    45  Bhargav     1    B      1    Z
1     2    47       is     4    i      4    Z
2     4    87     good    16    g     16    Z
3     5     5      boy    25    b     25    B
4     6    87    among    36    a     36    Z

In [27]:
df['col7'] = df['col5'].apply(lambda a: 'B' if a == 'b' else 'Z')
df

col1  col2     col3  col4 col5  col_4 col6 col7
0     1    45  Bhargav     1    B      1    Z    Z
1     2    47       is     4    i      4    Z    Z
2     4    87     good    16    g     16    Z    Z
3     5     5      boy    25    b     25    B    B
4     6    87    among    36    a     36    Z    Z

In [28]:
df['col8'] = df['col3'].apply(len)
df

col1  col2     col3  col4 col5  col_4 col6 col7  col8
0     1    45  Bhargav     1    B      1    Z    Z     7
1     2    47       is     4    i      4    Z    Z     2
2     4    87     good    16    g     16    Z    Z     4
3     5     5      boy    25    b     25    B    B     3
4     6    87    among    36    a     36    Z    Z     5

In [31]:
import math
df['col9'] = df['col2'].apply(math.log10)
df

col1  col2     col3  col4 col5  col_4 col6 col7  col8      col9
0     1    45  Bhargav     1    B      1    Z    Z     7  1.653213
1     2    47       is     4    i      4    Z    Z     2  1.672098
2     4    87     good    16    g     16    Z    Z     4  1.939519
3     5     5      boy    25    b     25    B    B     3  0.698970
4     6    87    among    36    a     36    Z    Z     5  1.939519

In [32]:
import numpy as np

In [33]:
l = ['bhargav',1,2,3,4,5 ]

In [34]:
type(l)

list

In [35]:
np.array(l)

array(['bhargav', '1', '2', '3', '4', '5'], dtype='<U11')

In [36]:
type(np.array(l))

numpy.ndarray

In [38]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [75]:
a = np.array([[1,2],[3,4]])

In [42]:
a[0][1]

2

In [48]:
np.array([1,2,3,4], ndmin=0)

array([1, 2, 3, 4])

In [49]:
np.array([1,2,3,4], ndmin=1)

array([1, 2, 3, 4])

In [50]:
np.array([1,2,3,4], ndmin=2)

array([[1, 2, 3, 4]])

In [51]:
np.array([1,2,3,4], ndmin=3)

array([[[1, 2, 3, 4]]])

In [54]:
a1 =np.array([1,2,3,4], ndmin=3)
print(a1)
print(a1[0])
print(a1[0][0])
print(a1[0][0][2])

[[[1 2 3 4]]]
[[1 2 3 4]]
[1 2 3 4]
3


In [55]:
 np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [56]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [57]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [61]:
np.mat([1,2,3,4,5]) # matrix at a minimun 2-dimentional, so it retunrs 2-dim data

matrix([[1, 2, 3, 4, 5]])

In [63]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [64]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [65]:
np.asanyarray(a) # converted list into array

array([1, 2, 3, 4, 5])

In [66]:
np.asanyarray(np.mat(a)) # kept the matrix as matrix only, doesn't change bcz matrix is a subclass of array

matrix([[1, 2, 3, 4, 5]])

In [67]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [69]:
np.fromfunction(lambda i,j: i*j, (3,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 1., 2., 3., 4.],
       [0., 2., 4., 6., 8.]])

In [70]:
np.fromfunction(lambda i,j: i*j, (3,5), dtype=int) 

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [71]:
np.mat(np.fromfunction(lambda i,j: i*j, (3,5), dtype=int) )

matrix([[0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4],
        [0, 2, 4, 6, 8]])

In [78]:
a =np.fromfunction(lambda i,j,k: i*j, (3,5,2), dtype=int) 

In [73]:
np.mat(np.fromfunction(lambda i,j,k: i*j*k, (3,5,2), dtype=int) )

ValueError: shape too large to be a matrix.

In [79]:
 a.ndim

3

In [80]:
a.size

30

In [81]:
a.shape

(3, 5, 2)

In [82]:
a.dtype

dtype('int32')

In [83]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(3, 5, 2)

In [84]:
a =np.fromfunction(lambda i,j: i*j, (3,5), dtype=int) 

In [85]:
pd.DataFrame(a)

0  1  2  3  4
0  0  0  0  0  0
1  0  1  2  3  4
2  0  2  4  6  8

When we have multi dimentional (dim>2) data, we need to flatten or reshape the data to make a pandas dataframe

In [86]:
np.random.rand(2,4,5)

array([[[0.64660058, 0.08553934, 0.11331239, 0.69234869, 0.40439817],
        [0.21107716, 0.65986292, 0.91832854, 0.65462801, 0.56176151],
        [0.74261726, 0.94281697, 0.03530454, 0.16153794, 0.09162356],
        [0.35195354, 0.5718599 , 0.16890507, 0.02644728, 0.32329736]],

       [[0.55136229, 0.01686471, 0.11836994, 0.94747727, 0.44627617],
        [0.76377349, 0.51360669, 0.36762187, 0.26407299, 0.28699091],
        [0.03178426, 0.53701549, 0.61600803, 0.61669843, 0.20253411],
        [0.99266191, 0.12678035, 0.73036104, 0.5680855 , 0.33220419]]])

In [93]:
np.random.randint(5,100)

56

In [94]:
np.random.randint(5,100,size = (3,5))

array([[33, 35, 75, 61, 69],
       [94, 27, 16, 93, 76],
       [51, 65, 72, 22,  9]])

In [95]:
np.random.randn(4,5)

array([[ 0.26687792, -1.74158238, -2.67961474,  0.76345588, -0.35673065],
       [-0.20958959, -1.1805378 , -0.84042052, -0.92729868,  1.74530888],
       [ 0.81228159,  1.16719097,  0.23594241,  0.36013763, -3.75333512],
       [ 1.05984336,  1.32344395, -0.34611017,  2.11533941, -0.01823211]])

In [96]:
pd.DataFrame(np.random.randn(100,57))

0         1         2         3         4         5         6   \
0   0.538248  0.040538 -0.110046  0.198128  0.559521 -1.348856 -0.485814   
1  -1.632339  0.921153 -1.242698 -2.030767  1.773807  0.130526  1.364712   
2  -1.442621  1.012364  0.402676  1.214451 -1.051799 -1.807450 -0.175220   
3  -0.600566  1.000107  0.412567 -0.057531  0.490958 -0.883959  1.222505   
4   0.973085  0.691311  1.912164  0.844752  0.096966 -0.374220 -0.172561   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.152948  0.638646 -0.791569 -0.014248 -0.782361 -1.045391  0.020806   
96  1.101624  0.323026 -0.911952  0.508105 -0.258002  0.501614 -0.402451   
97 -1.108377 -1.764742  0.826389 -0.267255  0.622562  1.728341 -0.405572   
98 -1.017729 -0.015218 -1.165361 -1.324817 -0.699301 -0.152875  1.377816   
99 -0.031319 -0.717019  0.096929 -1.759402 -0.723815 -0.037993 -0.110261   

          7         8         9   ...        47        48        49        50  \
0  -2.218262  0.376086 -0.950547  ...  0.139677 -0.605917  0.564505  0.139172   
1   2.679352  0.044036  0.678466  ...  0.164595 -2.708222  0.174249  0.105419   
2  -0.426675  0.656742  0.276018  ...  0.987993 -0.513594 -0.161556 -1.025723   
3  -1.098835  0.019526  2.052644  ...  0.854998 -1.035385  2.506237 -1.315223   
4   0.282074  0.064590 -1.842588  ...  0.324709 -2.459126 -0.214214 -0.344419   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  1.205940  0.843442  1.125992  ... -0.245295 -0.349253  0.744944  0.166886   
96 -1.725747  0.550433 -0.786338  ...  0.514574 -0.527022  1.614755 -0.322336   
97 -0.037065  0.246133 -0.964310  ...  0.307702  0.445267 -0.933427 -0.591832   
98  0.467455  0.234702 -2.186292  ...  0.610961  0.391952  0.391484 -0.248940   
99 -1.213348 -0.675542 -1.110932  ... -0.250427  1.193413  0.425389  0.021466   

          51        52        53        54        55        56  
0   1.402376 -0.647642 -0.789898 -0.659261 -0.212307  0.378329  
1  -0.512087 -0.258317  0.420616 -2.150891 -1.778949  1.413260  
2   0.544285  0.645652 -2.100085  2.084834  1.624244 -0.316720  
3   0.907548  0.440017  0.387645 -1.350714  0.105902  0.405861  
4  -0.280131  0.657437  0.176822  1.346535  0.863812 -0.112480  
..       ...       ...       ...       ...       ...       ...  
95  1.397874 -0.422648 -0.500737  0.217824 -0.907931 -0.559104  
96  0.747076  0.496187 -0.372478 -0.167671 -0.390898  0.239090  
97 -1.279022  0.323707  2.072497  2.005054 -0.171833 -0.991918  
98 -0.633727  0.687579 -1.081737 -0.358169  0.462970  1.376806  
99  1.776862 -1.920524  0.658233  0.010732  0.080151 -0.745033  

[100 rows x 57 columns]

In [97]:
a =np.fromfunction(lambda i,j,k: i*j, (3,5,2), dtype=int)  # this can't be a pd dataframe

In [99]:
pd.DataFrame(a.reshape(5,6))

0  1  2  3  4  5
0  0  0  0  0  0  0
1  0  0  0  0  0  0
2  1  1  2  2  3  3
3  4  4  0  0  2  2
4  4  4  6  6  8  8

In [103]:
a.reshape(3,-1).shape

(3, 10)

In [107]:
a.resize(3,-1)

ValueError: negative dimensions not allowed

In [109]:
a.reshape(5,-1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 2, 2, 3, 3],
       [4, 4, 0, 0, 2, 2],
       [4, 4, 6, 6, 8, 8]])

In [110]:
a.resize(3,10)

In [111]:
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 2, 2, 3, 3, 4, 4],
       [0, 0, 2, 2, 4, 4, 6, 6, 8, 8]])

In [113]:
list(range(4,15,2))

[4, 6, 8, 10, 12, 14]

In [114]:
list(range(4,15,0.2)) # range function accpets only integer values

TypeError: 'float' object cannot be interpreted as an integer

In [116]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [117]:
np.arange(4,5,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8])

In [118]:
a = np.arange(4,10,0.2)

In [119]:
a[2:12]

array([4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2])

In [125]:
arr

array([[0.99803843, 0.61648465, 0.94192697, 0.21520029, 0.63235094],
       [0.55999223, 0.55069834, 0.05995862, 0.89614937, 0.2199213 ],
       [0.21451943, 0.77328939, 0.9357006 , 0.22744885, 0.96130922],
       [0.61407742, 0.16291613, 0.16037783, 0.31677937, 0.78653627]])

In [126]:
arr[arr[:,:]>0.5]

array([0.99803843, 0.61648465, 0.94192697, 0.63235094, 0.55999223,
       0.55069834, 0.89614937, 0.77328939, 0.9357006 , 0.96130922,
       0.61407742, 0.78653627])

In [130]:
arr[1:3,2]

array([0.05995862, 0.9357006 ])

In [131]:
arr[1:3,2].shape

(2,)

In [132]:
arr[1:3,2:3].shape

(2, 1)

In [133]:
arr[[1,2],[2]]

array([0.05995862, 0.9357006 ])

In [134]:
arr[[1,2],[2]].shape

(2,)

In [141]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [143]:
a@b # '@' matrix multiplication

array([[10, 13],
       [22, 29]])

+,-,*,/ performs elememnt  wise operations in matrix

In [144]:
m = a@b

In [145]:
m/0

C:\Users\bharg\AppData\Local\Temp\ipykernel_7296\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])